### ISSUE TITLE
Download of dataset resources

### ISSUE THREAD

**Issue by pwalsh** [datopian/ckanext-montreal#2]
# Description

Users should be able to download data in a variety of formats. Also, users should ideally be able to download resources directly from the dataset page, rather than have to navigate to resource pages.

# Tasks

- [ ] Downloads for each dataset resource from the dataset page directly, and no additional navigation for this required to the resource pages
- [ ] Downloads for all auto-convertible format types to also be exposed (e.g.: CSV, TSV, JSON, XML for tabular datasets)

# Acceptance

- [ ] Can visit any dataset on staging site and download that data in multiple formats, that have been auto-converted from the original format
- [ ] All links to download resources are available from the dataset page, no additional navigation to resource pages required
