### ISSUE TITLE
Implement multilingual support

### ISSUE THREAD

**Issue by pwalsh** [datopian/ckanext-montreal#3]
# Description

The site must be fully available in both French and English.

# Tasks

- [ ] Enable French in CKAN config
- [ ] Check that language picker appears templates
- [ ] Install Fluent for multilingual content and metadata
- [ ] Configure fluent for French and English content fields

# Acceptance

- [ ] Can switch languages and navigate the site in each available language
- [ ] Content pages can have multiple languages (e.g.: about in French, and about in English) and the navigation works with the language selection
- [ ] Dataset schema fields are also translatable
