### ISSUE TITLE
Integrate data tracking and statistics

### ISSUE THREAD

**Issue by pwalsh** [datopian/ckanext-montreal#4]
# Description

We require basic tracking and analytics for the site.

# Tasks

- [ ] Client provides us with user access to their Google Analytics
- [ ] Integrate tracking code and check collecting data
- [ ] Verify with client that the data points they want to track are there

# Acceptance

- [ ] Staging site has google analytics
- [ ] We have access to the GA ID and account for the client
