### ISSUE TITLE
Investigate multilingual content integration via WordPress.com

### ISSUE THREAD

**Issue by pwalsh** [datopian/ckanext-montreal#5]
# Description

At Datopian we are moving to doing all content management for CKAN sites from wordpress.com, providing a superior content editing experience. We need to investigate doing this with multilingual sites.

# Tasks

- [ ] Investigate how multilingual content from wordpress is provided via the API
- [ ] Investigate how we will integration the multilingual responses from wordpress with the CKAN multilingual machinery

# Acceptance

- [ ] Short spec on multilingual content integration from wordpress to CKAN
- [ ] Estimate of time to implement this support, on top of our existing wordpress integration
