### ISSUE TITLE
Investigate dataset versioning options

### ISSUE THREAD

**Issue by pwalsh** [datopian/ckanext-montreal#8]
# Description

We need to investigate best approaches to dataset versioning, ideally, producing a best practice for how we will do this at Datopian on CKAN going forward. There is an [existing CKAN extension](https://github.com/aptivate/ckanext-datasetversions) which covers some dataset versioning use cases. Also on datahub.io our team has implemented data versioning in different ways leveraging cloud platforms.

# Tasks

- [ ] Collect a short set of user stories from the client on how they want to use dataset versioning, to flesh out the requirement further
- [ ] Look into existing approaches to dataset versioning in CKAN and outside, for alignment with the client user stories
- Write up a short spec on how we will approach dataset versioning

# Acceptance

- [ ] Spec and approach for dataset versioning that meets montreal's needs
