### ISSUE TITLE
Integrate org portals extension

### ISSUE THREAD

**Issue by pwalsh** [datopian/ckanext-montreal#9]
# Description

We need to use the org portals extension for enhanced org functionality.

# Tasks

- [ ] Get additional user stories from the client for how this is going to be used
- [ ] Integrate and configure [orgportals](https://github.com/ViderumGlobal/ckanext-orgportals)

# Acceptance

- [ ] Org Portals with example data live on staging
